Configuration and Drawable now ported

diff --git a/code/game/Makefile-python b/code/game/Makefile-python
--- a/code/game/Makefile-python
+++ b/code/game/Makefile-python
@@ -3,10 +3,20 @@ include ../common.mk
 .PHONY: clean check test
 
 check:
-	for pyfile in $$(/bin/ls -1 *.py); do   echo $$pyfile; pylint --errors-only $$pyfile || break ; done
+	for pyfile in $$(/bin/ls -1 *.py); \
+        do   echo "@@@@@@@@@@ Checking file $$pyfile @@@@@@@@@@"; \
+        pylint --errors-only $$pyfile \
+          && echo "\033[1;32mPASS - $$pyfile\033[0m" \
+          || echo "\033[1;31mFAILED - $$pyfile\033[0m" ;\
+        done
 
 test:
-	for pyfile in $$(/bin/ls -1 *.py); do   echo $$pyfile; ./$$pyfile || break ; done
+	for pyfile in $$(/bin/ls -1 *.py); \
+        do   echo "@@@@@@@@@@ Testing file $$pyfile @@@@@@@@@@"; \
+        ./$$pyfile \
+          && echo "\033[1;32mPASS - $$pyfile\033[0m" \
+          || echo "\033[1;31mFAILED - $$pyfile\033[0m" ;\
+        done
 
 clean:
 	rm -f *~ *.pyc *.pyo
