Move C++ code into deprecated directory

diff --git a/code/game/Makefile b/code/game/Makefile
--- a/code/game/Makefile
+++ b/code/game/Makefile
@@ -1,37 +1,22 @@
 include ../common.mk
 
-BOOSTCXXFLAGS :=
-BOOSTLDFLAGS := -lboost_thread
+.PHONY: clean check test
 
-XMLCXXFLAGS := -I /usr/include/libxml2
-XMLLDFLAGS := -lxml2
+check:
+	for pyfile in $$(/bin/ls -1 *.py); \
+        do   echo "@@@@@@@@@@ Checking file $$pyfile @@@@@@@@@@"; \
+        pylint --errors-only $$pyfile \
+          && echo "\033[1;32mPASS - $$pyfile\033[0m" \
+          || echo "\033[1;31mFAILED - $$pyfile\033[0m" ;\
+        done
 
-READLINECXXFLAGS :=
-READLINELDFLAGS := -lreadline
-
-GAMECXXFLAGS := $(CXXFLAGS) $(BOOSTCXXFLAGS) $(XMLCXXFLAGS) $(READLINECXXFLAGS)
-GAMELDFLAGS  := $(GAME_LIB_FLAGS) $(BOOSTLDFLAGS) $(XMLLDFLAGS) $(READLINELDFLAGS)
-
-.PHONY: clean
-
-OBJECTS = $(patsubst %.$(SOURCE_FILE_EXT), $(BIN_DIR)/%.$(OBJ_FILE_EXT),$(wildcard *.$(SOURCE_FILE_EXT)))
-
-EXES = $(patsubst %.$(MAIN_FILE_EXT), $(BIN_DIR)/%.$(EXE_FILE_EXT),$(wildcard *.$(MAIN_FILE_EXT)))
-
-all : $(BIN_DIR) $(EXES)
-
-$(BIN_DIR):
-	-mkdir $(BIN_DIR)
-
-$(EXES): $(BIN_DIR)/%.$(EXE_FILE_EXT) : %.$(MAIN_FILE_EXT) $(GAME_LIB_PATH)
-	$(CXX) $(CXXFLAGS) $(LDFLAGS) $< -o $@ ${OBJECTS} $(GAMECXXFLAGS) $(GAMELDFLAGS)
-
-$(OBJECTS) : $(BIN_DIR)/%.$(OBJ_FILE_EXT): %.$(SOURCE_FILE_EXT) *.$(HEADER_FILE_EXT)
-	$(CXX) $(GAMECXXFLAGS) -o $@ -c $<
-
-$(GAME_LIB_PATH) : $(OBJECTS)
-	ar -rsc $@ $(OBJECTS)
+test:
+	for pyfile in $$(/bin/ls -1 *.py); \
+        do   echo "@@@@@@@@@@ Testing file $$pyfile @@@@@@@@@@"; \
+        ./$$pyfile \
+          && echo "\033[1;32mPASS - $$pyfile\033[0m" \
+          || echo "\033[1;31mFAILED - $$pyfile\033[0m" ;\
+        done
 
 clean:
-	rm -f $(BIN_DIR)/*.$(ALL_EXE_FILE_EXT) $(BIN_DIR)/*.$(ALL_OBJ_FILE_EXT) $(BIN_DIR)/*.$(ALL_LIB_FILE_EXT)
-	-@rmdir $(BIN_DIR) 2> /dev/null
+	rm -f *~ *.pyc *.pyo
